export { Era } from './Era'
export { Faq } from './Faq'
export { Get_started } from './Get_started'
export { Header } from './Header'
export { How } from './How'
export { How_options } from './How_options'
export { Intro } from './Intro'
export { Invest } from './Invest'
export { Levels } from './Levels'
export { Levels_swiper } from './Levels_swiper'
export { Mobile_swiper } from './Mobile_swiper'

// profile
export { Profile_industry } from '@/components/shared/Profile__industry'
export { Profile_verification } from '@/components/shared/Profile__verification'
export { Profile_balance } from '@/components/shared/Profile_balance'
export { Profile_info } from '@/components/shared/Profile_info'
export { Profile_nav } from '@/components/shared/Profile_nav'
export { Profile_news } from '@/components/shared/Profile_news'
export { Profile_payments } from '@/components/shared/Profile_payments'
export { Profile_qr } from '@/components/shared/Profile_qr'
export { ProfileBurger_assets } from '@/components/shared/ProfileBurger_assets'
export { ProfileBurger_info } from '@/components/shared/ProfileBurger_info'
export { ProfileBurger_shortcuts } from '@/components/shared/ProfileBurger_shortcuts'
export { ProfileHeader } from '@/components/shared/ProfileHeader'
export { ProgileBurger_Tabsinfo } from '@/components/shared/ProgileBurger_Tabsinfo'
export { TapBar } from './TapBar'
