export { Era } from './Era'
export { Faq } from './Faq'
export { Get_started } from './Get_started'
export { Header } from './Header'
export { How } from './How'
export { How_options } from './How_options'
export { Intro } from './Intro'
export { Invest } from './Invest'
export { Levels } from './Levels.js'
export { Levels_swiper } from './Levels_swiper.js'
export { Mobile_swiper } from './Mobile_swiper'

// profile
export { ChartBlock } from './ChartBlock'
export { Profile_industry } from './Profile__industry'
export { Profile_verification } from './Profile__verification'
export { Profile_balance } from './Profile_balance'
export { Profile_info } from './Profile_info'
export { Profile_nav } from './Profile_nav'
export { ProfileHeader } from './ProfileHeader'
export { Profile_news } from './Profile_news'
export { Profile_payments } from './Profile_payments'
export { Profile_qr } from './Profile_qr'
export { ProfileBurger_info } from './ProfileBurger_info'
export { ProfileBurger_shortcuts } from './ProfileBurger_shortcuts'
export { ProfileBurger_assets } from './ProfileBurger_assets'
export { TapBar } from './TapBar'
export { ProgileBurger_Tabsinfo } from './ProgileBurger_Tabsinfo'
export {ProfileBurger_setMode} from './ProfileBurger_setMode'