export type SiteConfig = typeof siteConfig

export const siteConfig = {
	name: 'NextFi | Home',
	title: 'NextFi - Crypto Trading Platform',
	description:
		'NextFi is a secure, user-friendly crypto trading platform. Join us to start investing with confidence in a wide range of digital assets. Realize your financial potential with NextFi.',
	keywords: [
		'NextFi',
		'crypto trading',
		'cryptocurrency investment',
		'bitcoin trading',
		'crypto platform',
		'digital assets',
		'blockchain technology',
		'crypto exchange',
		'buy cryptocurrency',
		'sell bitcoin',
		'crypto wallet',
		'invest in cryptocurrency',
		'crypto portfolio',
		'digital currency trading',
		'ethereum trading',
		'crypto analysis',
		'crypto signals',
		'altcoin investment',
		'secure crypto trading',
		'crypto market insights',
		'cryptocurrency security',
		'stablecoin trading',
		'crypto beginners guide',
		'crypto market trends',
		'online crypto trading',
		'best crypto platform',
		'decentralized finance',
		'Defi trading',
		'crypto trading tools',
		'crypto investment strategies',
		'crypto trading app',
		'cryptocurrency platform for beginners',
	],
	openGraph: {
		title: 'NextFi - Crypto Trading Platform',
		description:
			'NextFi is a secure, user-friendly crypto trading platform. Join us to start investing with confidence in a wide range of digital assets. Realize your financial potential with NextFi.',
		url: 'https://www.nextfi.com',
		siteName: 'NextFi',
		images: [
			{
				url: 'https://www.nextfi.com/og-image.jpg',
				width: 1200,
				height: 630,
				alt: 'NextFi - Crypto Trading Platform',
			},
		],
		type: 'website',
	},
	twitter: {
		card: 'summary_large_image',
		site: '@NextFi',
		creator: '@NextFi',
	},
}
